'use strict';

const RollDicebtn = document.querySelector('.RollDicebtn');
const HoldScorebtn = document.querySelector('.Holdbtn');
const NewGamebtn = document.querySelector('.NewGamebtn');
const diceImageHolder = document.querySelector('.dice');
const player0 = document.querySelector('.player0');
const player1 = document.querySelector('.player1');


let players=[0,0];  // we will store the currentScores into global scores for 2 different player once they decide to hold the value.
let activePlayer = 0; //holds the information about which player is active
let diceNumber=0;   // score random number generated by dice [1,6].
let currentScore=0;
const maxscore=30;


const focusShifts = function(){
    currentScore=0;
    document.querySelector(`.currentScore-player${activePlayer}`).textContent = currentScore;
    player0.classList.toggle('active-player');
    player0.classList.toggle('deactive-player');
    player1.classList.toggle('active-player');
    player1.classList.toggle('deactive-player');
    activePlayer = activePlayer === 0 ? 1 : 0;
}




RollDicebtn.addEventListener('click',function(){

   // generate the random number and display dice image accordingly
    diceNumber = Number(Math.trunc(Math.random()*6)+1);
    diceImageHolder.src = `images/dice-${diceNumber}.jpg`;
    // remove the hidden property and allow dice image to be displayed
   diceImageHolder.classList.remove('hidden');

   // if the outcome is not 1 then add the diceNumber to the currentScore of the respective player.
   if(diceNumber!==1){
        currentScore+=diceNumber;
        document.querySelector(`.currentScore-player${activePlayer}`).textContent = currentScore;
   }
   else{
        //since we will be switching to the new player we will be doing 2 things here
        // 1) restore current-score of current player to 0.
        // 2) shift focus boxes
        // 3) change the active player status
      
        focusShifts();
   }
})
HoldScorebtn.addEventListener('click',function(){
    players[activePlayer]+=currentScore;
    document.querySelector(`.globalScore--player${activePlayer}`).textContent = players[activePlayer];
    console.log(document.querySelector(`.globalScore--player${activePlayer}`).textContent);


    if(document.querySelector(`.globalScore--player${activePlayer}`).textContent>=maxscore){
        document.querySelector(`.player${activePlayer}`).classList.add('winner');
        document.querySelector(`.p${activePlayer}`).style.color = 'white';
        RollDicebtn.classList.add('hidden');
        HoldScorebtn.classList.add('hidden');
        diceImageHolder.classList.add('hidden');
        document.querySelector(`.currentScore-player${activePlayer}`).textContent = 0;
    }
    else focusShifts();
})
NewGamebtn.addEventListener('click',function(){
    players[0]=0;
    players[1]=0;
    document.querySelector(`.globalScore--player0`).textContent = players[0];
    document.querySelector(`.globalScore--player1`).textContent = players[1];
    currentScore=0;
    document.querySelector(`.currentScore-player0`).textContent = currentScore;
    document.querySelector(`.currentScore-player1`).textContent = currentScore;
    RollDicebtn.classList.remove('hidden');
    HoldScorebtn.classList.remove('hidden');
    document.querySelector(`.player${activePlayer}`).classList.remove('winner');
    document.querySelector(`.p${activePlayer}`).style.color = 'black';
    player0.classList.add('active-player');
    player0.classList.remove('deactive-player');
    player1.classList.add('deactive-player');
    player1.classList.remove('active-player');
    activePlayer=0;
})
